<?php
namespace backend\controllers;

use common\models\Product;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'search'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (in_array($action->id, ['search']))
            $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->renderPartial('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            return $this->render('error', ['exception' => $exception]);
        }
    }

    public function actionSearch()
    {
        /*$q = Yii::$app->request->post(['q']);
        $rs = Yii::$app->db->createCommand("SELECT id,name,price_sale,avatar,code,stock FROM product WHERE search_term like '%:q%' AND status=:s ORDER BY name ASC LIMIT 10")
            ->bindParam(':q', $q)->bindValue(":s", Product::STATUS_ACTIVE)->queryAll();
        echo "<pre>";
        print_r($rs);
        echo "</pre>";
        die;*/
        $rs = [
            'total_count' => 5,
            'items' => [
                ['id' => 132, 'name' => "ASDASD", 'avatar_url' => 'https://avatars.githubusercontent.com/u/4596235?v=3'],
                ['id' => 134, 'name' => "nhfgnfgng", 'avatar_url' => 'https://avatars.githubusercontent.com/u/4596235?v=3'],
                ['id' => 1334, 'name' => "h5yh45yh", 'avatar_url' => 'https://avatars.githubusercontent.com/u/4596235?v=3'],
                ['id' => 13534, 'name' => "bdfne55yrty", 'avatar_url' => 'https://avatars.githubusercontent.com/u/4596235?v=3'],
            ]
        ];
        return Json::encode($rs);
    }

}
