<?php
/**
 * Created by PhpStorm.
 * User: Mitonios-Tofu
 * Date: 3/8/2016
 * Time: 3:46 PM
 */

namespace common\models;


use common\behaviors\UserBehavior;
use common\models\base\CustomerBase;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

class Customer extends CustomerBase
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            UserBehavior::className(),
            BlameableBehavior::className(),
        ];
    }

    public function beforeSave($insert)
    {
        $this->search_term = $this->code . "|" . $this->name . "|" . $this->phone;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (empty($this->code)) {
            $this->code = "C" . str_pad($this->id, 5, 0, STR_PAD_LEFT);
            $this->update();
        }
        return parent::afterSave($insert, $changedAttributes);
    }
}