<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 4/9/2016
 * Time: 12:14 PM
 */

namespace common\models;


use common\behaviors\UserBehavior;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\helpers\Json;

class PhieuXuatKho extends \common\models\base\PhieuXuatKho
{
    const STATUS_DRAFT = 0;
    const STATUS_FINISH = 1;

    const DELETED_TRUE = 1;
    const DELETED_FALSE = 0;

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className(),
            UserBehavior::className(),
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (empty($this->ma_phieu_xuat)) {
            $this->ma_phieu_xuat = "ET" . str_pad($this->id, 5, 0, STR_PAD_LEFT);//Import Ticket
            $this->update();
        }
        return parent::afterSave($insert, $changedAttributes);
    }

    public function afterFind()
    {
        $this->ngay_xuat = date("d/m/Y", strtotime($this->ngay_xuat));
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->ngay_xuat = date("Y-m-d", strtotime(str_replace("/", '-', $this->ngay_xuat)));

        if ($this->temp_data) {
            $this->tong_hang = $this->tong_gia_nhap = $this->tong_gia_ban = 0;
            $data = Json::decode($this->temp_data);
            foreach ($data as $item) {
                $this->tong_hang += $item['so_luong_xuat'];
                $this->tong_gia_nhap += $item['so_luong_xuat'] * $item['gia_nhap'];
                $this->tong_gia_ban += $item['so_luong_xuat'] * $item['gia_ban'];
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ma_phieu_xuat' => 'Mã phiếu',
            'ghi_chu' => 'Ghi chú',
            'status' => 'Status',
            'ngay_xuat' => 'Ngay Xuat',
            'dai_ly_id' => 'Đại Lý',
            'tong_hang' => 'Tong Hang',
            'tong_gia_nhap' => 'Tong Gia Nhap',
            'tong_gia_ban' => 'Tong Gia Ban',
            'deleted' => 'Deleted',
            'temp_data' => 'Temp Data',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }
}