<?php

namespace common\models;

use common\behaviors\UserBehavior;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

class PhieuNhapHang extends \common\models\base\PhieuNhapHang
{
    const STATUS_DRAFT = 0;
    const STATUS_FINISH = 1;

    const DELETED_TRUE = 1;
    const DELETED_FALSE = 0;

    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['ty_gia_cn_vn'], 'default', 'value' => 1],
        ]);
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className(),
            UserBehavior::className(),
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (empty($this->ma_phieu_nhap)) {
            $this->ma_phieu_nhap = "IT" . str_pad($this->id, 5, 0, STR_PAD_LEFT);//Import Ticket 
            $this->update();
        }
        return parent::afterSave($insert, $changedAttributes);
    }

    public function afterFind()
    {
        $this->ngay_nhap = date("d/m/Y", strtotime($this->ngay_nhap));
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->ngay_nhap = date("Y-m-d", strtotime(str_replace("/", '-', $this->ngay_nhap)));
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ma_phieu_nhap' => 'Mã phiếu nhập',
            'ghi_chu' => 'Ghi chú',
            'status' => 'Status',
            'ngay_nhap' => 'Ngày nhập',
            'nha_cung_cap_id' => 'Nhà cung cấp',
            'tong_hang' => 'Tong Hang',
            'tong_gia_nhap_tq' => 'Tong Gia Nhap Tq',
            'tong_gia_nhap_vn' => 'Tong Gia Nhap Vn',
            'ty_gia_cn_vn' => 'Ty Gia Cn Vn',
            'temp_data' => 'Temp Data',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'deleted' => 'Deleted',
        ];
    }
}
