<?php

namespace common\models;

use common\behaviors\UserBehavior;
use common\models\base\RltProductTicketProductImportBase;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;

class RltProductTicketProductImport extends RltProductTicketProductImportBase
{

    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            //[['price_sale', 'price_store', 'total_import'], 'default', 'value' => 0],
        ]);
    }

    public function beforeValidate()
    {
        $this->total_import = (int)str_replace([',', '.'], '', $this->total_import);
        $this->price_sale = (int)str_replace([',', '.'], '', $this->price_sale);
        $this->price_store = (int)str_replace([',', '.'], '', $this->price_store);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className(),
            UserBehavior::className(),
        ];
    }

}
