<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 4/8/2016
 * Time: 7:41 PM
 */

namespace common\models;


use common\behaviors\UserBehavior;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

class SanPham extends \common\models\base\SanPham
{
    const STATUS_DRAFT = 0;
    const STATUS_FINISH = 1;

    const DELETED_TRUE = 1;
    const DELETED_FALSE = 0;

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className(),
            UserBehavior::className(),
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (empty($this->ma_ban)) {
            $this->ma_ban = "PS" . str_pad($this->id, 5, 0, STR_PAD_LEFT);//Import Ticket
            $this->update();
        }
        return parent::afterSave($insert, $changedAttributes);
    }

    public function afterFind()
    {
        $this->ngay_xuat = date("d/m/Y", strtotime($this->ngay_xuat));
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->ngay_xuat = date("Y-m-d", strtotime(str_replace("/", '-', $this->ngay_xuat)));
        $this->search_term = $this->ma_goc . "|" . $this->ma_ban . "|" . $this->ten . "|" . $this->ghi_chu . "|" . $this->gia_nhap . "|" . $this->gia_ban;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function getStatusList($id = null)
    {
        $arr = [self::STATUS_DRAFT => 'Chưa sẵn sàng', self::STATUS_FINISH => "Sẵn sàng xuất kho"];
        return isset($id) ? isset($arr[$id]) ? $arr[$id] : "" : $arr;
    }
    
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ma_goc' => 'Ma Goc',
            'ma_ban' => 'Ma Ban',
            'ten' => 'Ten',
            'search_term' => 'Search Term',
            'gia_ban' => 'Gia Ban',
            'gia_nhap' => 'Gia Nhap',
            'avatar' => 'Avatar',
            'status' => 'Status',
            'ghi_chu' => 'Ghi Chu',
            'phieu_xuat_kho_id' => 'Phieu Xuat Kho ID',
            'cua_hang_id' => 'Cua Hang ID',
            'ngay_xuat' => 'Ngay Xuat',
            'deleted' => 'Deleted',
            'so_luong_ton' => 'So Luong Ton',
            'so_luong_nhap' => 'So Luong Nhap',
            'chuyen_muc_id' => 'Chuyen Muc ID',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }
}