<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2/24/2016
 * Time: 6:43 PM
 */

namespace common\models;


use common\behaviors\UserBehavior;
use common\models\base\TicketProductImportBase;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

class TicketProductImport extends TicketProductImportBase
{
    const STATUS_DRAFT = 0;
    const STATUS_FINISH = 1;
    const STATUS_DELETE = 2;

    public function getItems()
    {
        return RltProductTicketProductImport::find()->where(['ticket_id' => $this->id])->all();
    }

    public function getTotalPriceStore()
    {
        $rs = 0;
        if (!$this->isNewRecord) {
            $rs = \Yii::$app->db->createCommand("SELECT SUM(price_store*total_import) AS result FROM rlt_product_ticket_product_import WHERE ticket_id=" . $this->id)->queryOne();
            $rs = $rs['result'];
        }
        return $rs;
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            BlameableBehavior::className(),
            UserBehavior::className(),
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (empty($this->code)) {
            $this->code = "TI" . str_pad($this->id, 0, 0, STR_PAD_LEFT);
            $this->update();
        }
        return parent::afterSave($insert, $changedAttributes);
    }

    public function afterFind()
    {
        $this->date_import = date("d/m/Y", strtotime($this->date_import));
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->date_import = date("Y-m-d", strtotime(str_replace("/", '-', $this->date_import)));
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}